#!/bin/sh
set -e
if ! getent passwd rusty-photon > /dev/null; then
    adduser --system --group --home /var/lib/rusty-photon --quiet rusty-photon
fi
install -d -m 0750 -o rusty-photon -g rusty-photon /var/lib/rusty-photon
if [ ! -e /etc/rusty-photon ]; then
    ln -s /var/lib/rusty-photon/.config/rusty-photon /etc/rusty-photon
fi
#DEBHELPER#
