//! Error type for the pa-scops-oag driver.
//!
//! The Scops OAG's failure modes are exactly the shared transport-driver common
//! core — no device-specific variants — so the enum, its ASCOM classification,
//! `From<TransportError>`, and the `Result` alias are all generated by
//! [`rusty_photon_driver::driver_error!`]. The codec-layer
//! `From<SessionError<ScopsCodecError>>` lives in [`crate::codec`] and targets
//! this (local) enum.

rusty_photon_driver::driver_error! {
    /// Errors that can occur when interacting with the Pegasus Astro Scops OAG.
    pub enum ScopsOagError {}
}
