//! # touptek-rs — safe Rust bindings for the ToupTek ToupCam camera SDK
//!
//! Sibling crate to [`zwo-rs`](https://crates.io/crates/zwo-rs) and
//! [`qhyccd-rs`](https://crates.io/crates/qhyccd-rs). It wraps the raw FFI in
//! `libtoupcam-sys` — generated by `bindgen` from the vendored ToupTek SDK header
//! — in a safe, ergonomic API. It will be consumed by rusty-photon's
//! `touptek-camera` ASCOM Alpaca driver (see `docs/plans/touptek-driver.md`).
//!
//! The same flat C ABI is shared by every OEM rebrand of the SDK (Altair, Omegon,
//! Meade, Bresser, Mallincam, RisingCam/Ogma, SVBony, StarShootG, Nncam, Tscam)
//! with only the `Toupcam_` symbol prefix swapped.
//!
//! ## Status
//!
//! **Phase B skeleton.** Enumeration ([`Sdk::enumerate`]), the [`Camera`] handle
//! (open, config setters, temperature read), and — the centrepiece — the
//! **callback → blocking bridge** for pull-mode/trigger exposures
//! ([`Camera::start_pull_mode`] / [`Camera::trigger_single`] /
//! [`Camera::wait_for_event`] / [`Camera::pull_image`]) are wired. The full ASCOM
//! surface (cooling control, RAW readout pixel formats, ST4 guiding, sensor type)
//! is filled in by the driver in later phases.
//!
//! ## `simulation` feature
//!
//! Mirrors zwo-rs/qhyccd-rs: a hardware-free, in-Rust simulated camera for
//! development and tests. As with those, the SDK is still *linked* when the
//! feature is on — it removes the hardware, not the link. With the feature on the
//! SDK is never called: enumeration reports [`SIM_CAMERA_COUNT`] and the camera
//! fabricates frames.
//!
//! ## Build requirements
//!
//! - **libclang** — `libtoupcam-sys` runs `bindgen` at build time (needed for
//!   `check`/`clippy`/build; *not* the SDK).
//! - **The ToupTek SDK** (`libtoupcam`) on the link path — needed to *link* (i.e.
//!   `build`/`test` a binary), even with the `simulation` feature, unless
//!   `TOUPCAM_SKIP_NATIVE_LINK=1` is set.

/// Raw, unsafe FFI bindings (`bindgen`). Prefer the safe API in this crate.
pub use libtoupcam_sys as sys;

mod camera;
mod error;
#[cfg(not(feature = "simulation"))]
mod ffi_util;

pub use camera::{Camera, CameraInfo, Event, Frame};
pub use error::{hr_check, Error, Result, SdkError};

/// Number of simulated cameras presented when the `simulation` feature is on.
#[cfg(feature = "simulation")]
pub const SIM_CAMERA_COUNT: usize = 1;

/// Entry point to the ToupTek SDK.
///
/// Enumerates connected cameras and opens them. With the `simulation` feature, a
/// fixed simulated camera is reported and the native SDK is never called (though
/// it is still linked — see the crate docs).
#[derive(Debug, Default)]
pub struct Sdk {
    _private: (),
}

impl Sdk {
    /// Initialise the SDK.
    ///
    /// # Errors
    /// Currently infallible, but returns [`Result`] so future initialisation can
    /// surface failures without an API break.
    pub fn new() -> Result<Self> {
        tracing::debug!("initialising ToupTek SDK");
        Ok(Self { _private: () })
    }

    /// Number of connected cameras.
    ///
    /// # Errors
    /// Propagates an enumeration failure on the real path; infallible under
    /// `simulation`.
    pub fn camera_count(&self) -> Result<usize> {
        #[cfg(feature = "simulation")]
        let count = SIM_CAMERA_COUNT;
        #[cfg(not(feature = "simulation"))]
        let count = self.enumerate()?.len();
        Ok(count)
    }

    /// Enumerate connected cameras (`Toupcam_EnumV2`).
    ///
    /// # Errors
    /// Infallible today; returns [`Result`] for forward compatibility (a future
    /// init/version check may fail).
    pub fn enumerate(&self) -> Result<Vec<CameraInfo>> {
        #[cfg(feature = "simulation")]
        {
            Ok(vec![CameraInfo {
                id: "sim-0".to_owned(),
                display_name: "Simulated ToupTek Camera".to_owned(),
                model_name: "ToupTek Simulator".to_owned(),
                flag: u64::from(sys::TOUPCAM_FLAG_TEC),
                pixel_size_x: 3.76,
                pixel_size_y: 3.76,
            }])
        }
        #[cfg(not(feature = "simulation"))]
        {
            // SAFETY: `arr` is a fixed `TOUPCAM_MAX`-element array of POD structs
            // (zeroed is a valid bit pattern); `Toupcam_EnumV2` fills up to that
            // many entries and returns the count.
            let mut arr: [sys::ToupcamDeviceV2; sys::TOUPCAM_MAX as usize] =
                unsafe { std::mem::zeroed() };
            let count = unsafe { sys::Toupcam_EnumV2(arr.as_mut_ptr()) } as usize;
            let count = count.min(arr.len());
            Ok(arr.iter().take(count).map(device_info).collect())
        }
    }

    /// Open the camera at enumeration `index`.
    ///
    /// # Errors
    /// [`Error::DeviceNotFound`] if no camera is present at `index` or the handle
    /// cannot be opened.
    pub fn open(&self, index: usize) -> Result<Camera> {
        let info = self
            .enumerate()?
            .into_iter()
            .nth(index)
            .ok_or(Error::DeviceNotFound)?;
        Camera::open_by_index(index as u32, info)
    }
}

/// Convert a raw enumerated `ToupcamDeviceV2` (+ its model) into [`CameraInfo`].
#[cfg(not(feature = "simulation"))]
fn device_info(dev: &sys::ToupcamDeviceV2) -> CameraInfo {
    use crate::ffi_util::c_string_field;

    let id = c_string_field(&dev.id);
    let display_name = c_string_field(&dev.displayname);
    let (model_name, flag, pixel_size_x, pixel_size_y) = if dev.model.is_null() {
        (String::new(), 0, 0.0, 0.0)
    } else {
        // SAFETY: `model` points to a static `ToupcamModelV2` owned by the SDK for
        // the lifetime of enumeration; we only read it.
        let model = unsafe { &*dev.model };
        let name = if model.name.is_null() {
            String::new()
        } else {
            // SAFETY: `name` is a static, NUL-terminated SDK-owned string.
            unsafe { std::ffi::CStr::from_ptr(model.name) }
                .to_string_lossy()
                .into_owned()
        };
        (name, model.flag, model.xpixsz, model.ypixsz)
    };

    CameraInfo {
        id,
        display_name,
        model_name,
        flag,
        pixel_size_x,
        pixel_size_y,
    }
}

#[cfg(feature = "simulation")]
pub mod simulation {
    //! Hardware-free, in-Rust simulation helpers (no SDK calls).
    use rand::RngExt;

    /// One 16-bit noise sample — a placeholder for a simulated sensor pixel.
    #[must_use]
    pub fn noise_sample() -> u16 {
        rand::rng().random()
    }

    /// Fill `buf` with simulated sensor noise as fast as possible.
    ///
    /// A seeded xorshift64 (a few integer ops per 8 bytes) — fast even in debug
    /// builds and single-core, so it cannot trip ConformU's 10 s `StartExposure`
    /// timeout the way a per-byte RNG or a core-grabbing parallel fill can. This
    /// is placeholder sensor noise, seeded per frame so frames differ
    /// run-to-run; quality is irrelevant. (Lesson carried from zwo-rs.)
    pub fn fill_noise(buf: &mut [u8]) {
        let mut state = rand::rng().random::<u64>() | 1;
        for chunk in buf.chunks_mut(8) {
            state ^= state << 13;
            state ^= state >> 7;
            state ^= state << 17;
            chunk.copy_from_slice(&state.to_le_bytes()[..chunk.len()]);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sdk_new_succeeds() {
        Sdk::new().unwrap();
    }

    #[test]
    fn enumeration_returns_a_count() {
        let sdk = Sdk::new().unwrap();
        let count = sdk.camera_count().unwrap();
        #[cfg(feature = "simulation")]
        assert_eq!(count, SIM_CAMERA_COUNT);
        // Without the simulation feature this calls the real SDK; with no hardware
        // attached the count is zero, but the call must not panic.
        #[cfg(not(feature = "simulation"))]
        let _ = count;
    }

    #[test]
    fn hr_check_treats_nonnegative_as_success() {
        hr_check(0).unwrap(); // S_OK
        hr_check(1).unwrap(); // S_FALSE is also success
    }

    #[test]
    fn hr_check_maps_known_and_unknown_failures() {
        assert_eq!(
            hr_check(0x8000_4001_u32 as i32).unwrap_err(),
            Error::Sdk(SdkError::NotImplemented)
        );
        assert_eq!(
            hr_check(0x8007_0057_u32 as i32).unwrap_err(),
            Error::Sdk(SdkError::InvalidArg)
        );
        match hr_check(0x8000_1234_u32 as i32).unwrap_err() {
            Error::Sdk(SdkError::Unknown(_)) => {}
            other => panic!("expected Unknown, got {other:?}"),
        }
    }

    #[cfg(feature = "simulation")]
    #[test]
    fn simulation_fill_noise_fills_buffer() {
        let mut buf = vec![0u8; 4096];
        simulation::fill_noise(&mut buf);
        assert!(buf.iter().any(|&b| b != 0));
    }

    #[cfg(feature = "simulation")]
    #[test]
    fn simulation_noise_sample_runs() {
        let _ = simulation::noise_sample();
    }
}
