//! Error type for the qhy-focuser driver.
//!
//! The Q-Focuser's failure modes are the shared transport-driver common core
//! plus one device-specific variant (`MoveFailed`), so the enum, its ASCOM
//! classification, `From<TransportError>`, and the `Result` alias are all
//! generated by [`rusty_photon_driver::driver_error!`]. The codec-layer
//! `From<SessionError<QhyCodecError>>` lives in [`crate::codec`] and targets
//! this (local) enum.

rusty_photon_driver::driver_error! {
    /// Errors that can occur when interacting with the QHY Q-Focuser.
    pub enum QhyFocuserError {
        #[error("move failed: {0}")]
        MoveFailed(String),
    }
}
