//! Error type for the ppba-driver.
//!
//! The PPBA's failure modes are the shared transport-driver common core plus
//! three switch-specific variants (`InvalidSwitchId`, `SwitchNotWritable`,
//! `AutoDewEnabled`). The enum, its ASCOM classification, `From<TransportError>`,
//! and the `Result` alias are all generated by
//! [`rusty_photon_driver::driver_error!`]. The codec-layer
//! `From<SessionError<PpbaCodecError>>` lives in [`crate::codec`] and targets
//! this (local) enum.

rusty_photon_driver::driver_error! {
    /// Errors that can occur when interacting with the PPBA device.
    pub enum PpbaError {
        #[error("invalid switch ID: {0}")]
        InvalidSwitchId(usize),
        #[error("switch not writable: {0}")]
        SwitchNotWritable(usize),
        #[error("cannot write to switch {0} while auto-dew is enabled. Disable auto-dew (switch 5) first.")]
        AutoDewEnabled(usize),
    }
    ascom {
        Self::InvalidSwitchId(_) => INVALID_VALUE,
        Self::SwitchNotWritable(_) => NOT_IMPLEMENTED,
    }
}
